"use client";

import { useEffect, useState } from "react";

export function BrutalistFooter() {
  const [randomText, setRandomText] = useState("");
  const [isGlitching, setIsGlitching] = useState(false);

  useEffect(() => {
    const phrases = [
      "EMBRACE THE CHAOS",
      "BRUTALISM NEVER DIES",
      "AI GENERATED MADNESS",
      "RANDOM IS BEAUTIFUL",
      "DESTROY THE GRID",
      "BOLD OR NOTHING",
      "CHAOS THEORY APPLIED",
      "BRUTALIST MANIFESTO",
    ];

    const interval = setInterval(() => {
      setIsGlitching(true);
      setTimeout(() => {
        setRandomText(phrases[Math.floor(Math.random() * phrases.length)]);
        setIsGlitching(false);
      }, 200);
    }, 3000);

    // Set initial text
    setRandomText(phrases[0]);

    return () => clearInterval(interval);
  }, []);

  return (
    <footer className="bg-black text-white py-20 relative overflow-hidden">
      {/* Brutal background shapes */}
      <div className="absolute inset-0">
        <div className="absolute top-0 left-0 w-full h-2 bg-red-500" />
        <div className="absolute top-2 left-0 w-full h-2 bg-yellow-400" />
        <div className="absolute top-4 left-0 w-full h-2 bg-blue-500" />
        <div className="absolute top-6 left-0 w-full h-2 bg-green-500" />
      </div>

      <div className="container mx-auto px-4 relative z-10">
        {/* Main footer content */}
        <div className="text-center mb-16">
          <h2
            className={`text-4xl md:text-6xl font-black uppercase font-mono mb-8 transition-all duration-200 ${
              isGlitching ? "transform scale-110 text-red-500" : "text-white"
            }`}
          >
            {isGlitching ? "████████████" : randomText}
          </h2>

          <div className="max-w-4xl mx-auto">
            <p className="text-xl md:text-2xl font-bold font-mono leading-relaxed mb-8">
              THIS SITE IS POWERED BY ARTIFICIAL INTELLIGENCE AND BRUTALIST
              DESIGN PRINCIPLES. EVERY VISIT GENERATES NEW CHAOS. EMBRACE THE
              RANDOMNESS.
            </p>
          </div>
        </div>

        {/* Brutal grid layout */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-16">
          <div className="bg-red-500 text-white p-8 border-8 border-yellow-400 transform rotate-2">
            <h3 className="text-3xl font-black uppercase font-mono mb-4">
              RANDOM
            </h3>
            <p className="font-mono text-lg">
              Every element on this page is generated by AI. Nothing is
              permanent. Everything changes.
            </p>
          </div>

          <div className="bg-blue-500 text-white p-8 border-8 border-red-500 transform -rotate-1">
            <h3 className="text-3xl font-black uppercase font-mono mb-4">
              BRUTAL
            </h3>
            <p className="font-mono text-lg">
              Raw, uncompromising design. Bold colors. Sharp edges. No subtlety
              allowed.
            </p>
          </div>

          <div className="bg-yellow-400 text-black p-8 border-8 border-blue-500 transform rotate-1">
            <h3 className="text-3xl font-black uppercase font-mono mb-4">
              CHAOS
            </h3>
            <p className="font-mono text-lg">
              Organized disorder. Controlled randomness. Beautiful destruction
              of conventions.
            </p>
          </div>
        </div>

        {/* Footer bottom */}
        <div className="text-center border-t-8 border-white pt-8">
          <div className="flex flex-col md:flex-row justify-between items-center gap-4">
            <div className="text-2xl font-black uppercase font-mono">
              © 2024 BRUTAL AI
            </div>

            <div className="flex gap-4">
              <div className="w-12 h-12 bg-red-500 border-4 border-white transform rotate-45" />
              <div className="w-12 h-12 bg-blue-500 border-4 border-white" />
              <div className="w-12 h-12 bg-yellow-400 border-4 border-white rounded-full" />
              <div className="w-12 h-12 bg-green-500 border-4 border-white transform -rotate-45" />
            </div>

            <div className="text-xl font-black uppercase font-mono">
              POWERED BY A LLAMA
            </div>
          </div>
        </div>
      </div>

      {/* Brutal corner decorations */}
      <div className="absolute bottom-0 left-0 w-0 h-0 border-l-[80px] border-l-transparent border-t-[80px] border-t-red-500" />
      <div className="absolute bottom-0 right-0 w-0 h-0 border-r-[80px] border-r-transparent border-t-[80px] border-t-blue-500" />
    </footer>
  );
}
